---
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.1'
      - run: node --version
      - run: yarn build
workflows:
  test_my_app:
    jobs:
      - install-node-example
